# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HotFixDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for HotFixDemo

  pod 'Aspects'

  target 'HotFixDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HotFixDemoUITests' do
    # Pods for testing
  end

end
